### ISSUE TITLE
Pagination previous/next ::after elements are vertically misaligned

### ISSUE THREAD

**Issue by deneboulton** [red-gate/honeycomb-web-toolkit#106]
See screenshot:

![image](https://cloud.githubusercontent.com/assets/2387822/20094455/2bcd2a6a-a599-11e6-8d1e-d49909fbce7a.png)

**Comment by edwardcasbon** [comment]
Fixed in https://github.com/red-gate/honeycomb-web-toolkit/releases/tag/v8.0.11
