### ISSUE TITLE
Serve packages from cdn.rd.gt instead of cdnjs.cloudflare.com

### ISSUE THREAD

**Issue by rmc47** [red-gate/honeycomb-web-toolkit#121]
[Low priority]

Cloudflare set some cookies at their root domain, including a Google Analytics cookie, which means if you've visited their site in the past, they also get sent back by any future requests for assets from cdnjs.cloudflare.com.

Could we serve some of these dependencies from cdn.rd.gt instead of cdnjs.cloudflare.com so they're truly cookieless?

(Noticed on babel-polyfill, but think there might be a couple of similar examples.)

**Comment by edwardcasbon** [comment]
Thanks for the info @rmc47 ! I've now updated those resources, and have made a note to do the same on the Redgate website too.
