### ISSUE TITLE
We make significant use of jQuery but don't declare it as a dependency

### ISSUE THREAD

**Issue by ChrisLambrou** [red-gate/honeycomb-web-toolkit#137]
A [code search](https://codesearch.red-gate.com/?q=(%5C%24%5C.)%7C(j%5BQq%5Duery%5C.)&i=nope&files=&repos=honeycomb-web-toolkit) reveals that we make significant use of jQuery, yet we don't declare an explicit or implicit dependency on it. It doesn't appear in either [package.json](https://github.com/red-gate/honeycomb-web-toolkit/blob/master/package.json) or [package-lock.json](https://github.com/red-gate/honeycomb-web-toolkit/blob/master/package-lock.json).

In SQL Monitor, we're looking to migrate from jQuery v2 to v3, a breaking change. Some failed tests revealed that the removal of the `success`, `error` and `complete` methods from `jqXHR` has affected us. During our investigation, we spotted that the [3rd party Confluence jQuery scroll tree](https://github.com/red-gate/honeycomb-web-toolkit/blob/master/src/confluence/vendor/jquery.scroll-tree.js#L58) script in this repo may break in the move from jQuery v2 to v3. We haven't yet looked at other breaking changes, and it's quite possible that there are other issues in Honeycomb Web Toolkit.

Ideally, it would be great for Honeycomb Web Toolkit to have an explicitly declared dependency on jQuery, with an idea about which versions are supported (if we can't support both v2 and v3, our preference would be v3, since that's where vulnerabilities are being addressed).

**Comment by edwardcasbon** [comment]
Hi @ChrisLambrou , I've been taking a look at this today, and I've updated the web toolkit to use the latest version of jQuery, as well as add jQuery as a peer dependency. 

We still need to do some testing around the vendor scripts, so until we get chance to do that I'll keep this as a pending change. I'll hopefully be able to take a look again next Friday during my Honeycomb time.
