### ISSUE TITLE
font-size on .notification__icon means icon isn't centred.

### ISSUE THREAD

**Issue by rba100** [red-gate/honeycomb-web-toolkit#17]
http://honeycomb.red-gate.com/toolkit/#notifications

The left-hand icon isn't vertically centred. This affects image-based icons as well as font-based ones. The CSS currently sets the font-size to 24px / 1.5rem. To be centred, use the same font-size as the notification body or employ dark trickery.

**Comment by edwardcasbon** [comment]
Linked to https://github.com/red-gate/honeycomb-web-toolkit/issues/23, which has been resolved.
