### ISSUE TITLE
Icons for notifications aren't positioned quite right

### ISSUE THREAD

**Issue by wapadam** [red-gate/honeycomb-web-toolkit#23]
For the notification classes the icons aren't centred with the first line of text in the notification body. They are sunk below the level of the notification body.

Can't tell whether this is to do with the <figure> or <span> that are being used to display the icon.

**Comment by chrisdcmoore** [comment]
*bump*

**Comment by edwardcasbon** [comment]
This should now be fixed in the latest build of master.
