### ISSUE TITLE
HTML cheatsheet

### ISSUE THREAD

**Issue by edwardcasbon** [red-gate/honeycomb-web-toolkit#83]
Build a cheatsheet of classes defined in the Honeycomb web toolkit to make it easy for someone who's picking it up to know what classes they can use.

**Comment by deneboulton** [comment]
OOO, I was just going to suggest this to you at breakfast and forgot!!!!

I would love even just a simple list of all the classes - github search ain't the best

**Comment by edwardcasbon** [comment]
This is now in the latest release (`v10.1.0`), as `dist/honeycomb.css.cheatsheet.html`.
