### ISSUE TITLE
sticky-container does not reduce in height when reverting to a large screen size

### ISSUE THREAD

**Issue by deneboulton** [red-gate/honeycomb-web-toolkit#89]
1. use the class sticky-container, this is already used on red-gate.com
2. E.g. On red-gate.com - resize browser to a small breakpoint screen size which causes the menu to be laid out vertically thus increasing the vertical height
3. Resize back to a large breakpoint and the increased height remains.

Screenshot showing this issue:
![image](https://cloud.githubusercontent.com/assets/2387822/17618641/cf1ba270-6078-11e6-8866-c08da321d491.png)

**Comment by edwardcasbon** [comment]
The fix for this is in the latest jquery.sticky.js which has been included in Honeycomb Web toolkit v10.0.10 (https://github.com/red-gate/honeycomb-web-toolkit/releases/tag/v10.0.10) and is being deployed to the Redgate website now.
