### ISSUE TITLE
table--responsive's first child <td> has unnecessary margin-top

### ISSUE THREAD

**Issue by deneboulton** [red-gate/honeycomb-web-toolkit#90]
See screenshot below that shows this issue (screenshot also shows another issue that I have created a separate report for):

![image](https://cloud.githubusercontent.com/assets/2387822/17618701/1e389d9a-6079-11e6-9539-cabf602120aa.png)

**Comment by edwardcasbon** [comment]
Fixed in v10.0.9 (https://github.com/red-gate/honeycomb-web-toolkit/releases/tag/v10.0.9)
